### ISSUE TITLE
[ItemEditor] Move the window by double-clicking(in left corner)

### ISSUE THREAD

**Issue by zevladnit** [HoloVector/DoF.Issues#81]
![image](https://user-images.githubusercontent.com/18499429/27179753-a062bade-51d8-11e7-800a-59e0a9917482.png)
![image](https://user-images.githubusercontent.com/18499429/27179764-b0865c2c-51d8-11e7-8283-82d13fa2dded.png)

**Comment by AnotherAltr** [comment]
ХаХаха14:41, 15 июня 2017 г., zevladnit <notifications@github.com>:


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by AnotherAltr** [comment]
Это нормально
Наверное

**Comment by zevladnit** [comment]
#38
