### ISSUE TITLE
[ItemEditor]Create weapons from a magic element without attack type

### ISSUE THREAD

**Issue by zevladnit** [HoloVector/DoF.Issues#83]
![image](https://user-images.githubusercontent.com/18499429/27180041-14477790-51da-11e7-99fe-64b40e95dfa6.png)

**Comment by zevladnit** [comment]
#38

**Comment by AnotherAltr** [comment]
Ну и че?

**Comment by AnotherAltr** [comment]
Сохранить у тебя не получится

**Comment by AnotherAltr** [comment]
Не вижу проблемы

**Comment by zevladnit** [comment]
проблема как раз в том что я могу это сделать(сохранить)
